CREATE TABLE `blogentry` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(50) NULL DEFAULT NULL,
	`content` VARCHAR(50) NULL DEFAULT NULL,
	`author` VARCHAR(50) NULL DEFAULT NULL,
	`created` DATE NULL DEFAULT NULL,
	`fileid`  VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)